import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import UserProvider from "./context/user-context";
import DashboardProvider from "./context/dashboard-context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <UserProvider>
          <DashboardProvider>
            {children}
            <ToastContainer />
          </DashboardProvider>
        </UserProvider>
      </body>
    </html>
  );
}
